import { google } from "googleapis";
import PDFDocument from "pdfkit";
import * as XLSX from "xlsx";
import { env } from "@/env";
import { getFinanceOverview } from "@/lib/finance-service";
import {
  compareGames,
  getDashboardData,
  getGameByAppId,
  getOpportunityFinderData,
  getPlayerHistory,
  getPriceHistory,
  getReviewHistory,
  searchGames
} from "@/lib/game-service";
import { getProjectById } from "@/lib/project-service";
import { db } from "@/lib/db";

type ExportValue = string | number | boolean | null;
type ExportRow = Record<string, ExportValue>;

export interface ExportWorkbook {
  fileName: string;
  title: string;
  sheets: Array<{
    name: string;
    rows: ExportRow[];
  }>;
}

function formatCurrency(value: number | bigint | null | undefined) {
  if (value === null || value === undefined) {
    return "";
  }

  return (Number(value) / 100).toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0
  });
}

function formatDate(value: Date | string | null | undefined) {
  if (!value) {
    return "";
  }

  return new Date(value).toISOString();
}

function toNumber(value: number | bigint | null | undefined) {
  return value === null || value === undefined ? 0 : Number(value);
}

function average(values: number[]) {
  if (values.length === 0) {
    return 0;
  }

  return values.reduce((sum, value) => sum + value, 0) / values.length;
}

function median(values: number[]) {
  if (values.length === 0) {
    return 0;
  }

  const sorted = [...values].sort((left, right) => left - right);
  const middle = Math.floor(sorted.length / 2);

  return sorted.length % 2 === 0 ? (sorted[middle - 1] + sorted[middle]) / 2 : sorted[middle];
}

function getSignalLabel(score: number | null | undefined, reviewCount: number | null | undefined) {
  if ((score ?? 0) >= 85 && (reviewCount ?? 0) >= 500) {
    return "Quality leader";
  }

  if ((score ?? 0) >= 80 && (reviewCount ?? 0) < 500) {
    return "Niche proof";
  }

  if ((reviewCount ?? 0) >= 5000) {
    return "Demand anchor";
  }

  if ((score ?? 0) < 70 && (reviewCount ?? 0) >= 500) {
    return "Demand with quality risk";
  }

  return "Watchlist";
}

function sanitizeSheetName(value: string) {
  return value.replace(/[\\/*?:[\]]/g, " ").slice(0, 31) || "Sheet1";
}

function getSheetRows(rows: ExportRow[]) {
  if (rows.length > 0) {
    return rows;
  }

  return [{ message: "No data available for this export." }];
}

function getSheetHeaders(rows: ExportRow[]) {
  return Array.from(
    getSheetRows(rows).reduce((keys, row) => {
      for (const key of Object.keys(row)) {
        keys.add(key);
      }

      return keys;
    }, new Set<string>())
  );
}

function getColumnWidths(rows: ExportRow[]) {
  const sample = getSheetRows(rows);
  const keys = Object.keys(sample[0] ?? {});

  return keys.map((key) => {
    const contentWidth = Math.max(
      key.length,
      ...sample.map((row) => String(row[key] ?? "").length)
    );

    return {
      wch: Math.min(Math.max(contentWidth + 2, 12), 48)
    };
  });
}

export function createWorkbookBuffer(workbook: ExportWorkbook) {
  const book = XLSX.utils.book_new();

  for (const sheet of workbook.sheets) {
    const rows = getSheetRows(sheet.rows);
    const worksheet = XLSX.utils.json_to_sheet(rows);
    worksheet["!cols"] = getColumnWidths(rows);
    XLSX.utils.book_append_sheet(book, worksheet, sanitizeSheetName(sheet.name));
  }

  return XLSX.write(book, {
    type: "buffer",
    bookType: "xlsx"
  });
}

export function createCsvText(workbook: ExportWorkbook) {
  const firstSheet = workbook.sheets[0];
  const worksheet = XLSX.utils.json_to_sheet(getSheetRows(firstSheet?.rows ?? []));
  return XLSX.utils.sheet_to_csv(worksheet);
}

function ensurePdfSpace(doc: PDFKit.PDFDocument, minimumHeight = 72) {
  if (doc.y <= doc.page.height - doc.page.margins.bottom - minimumHeight) {
    return;
  }

  doc.addPage();
}

export function createPdfBuffer(workbook: ExportWorkbook) {
  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 48,
      info: {
        Title: workbook.title,
        Author: "Neolytics"
      }
    });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(24).fillColor("#111827").text(workbook.title);
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor("#6b7280").text(`Generated by Neolytics on ${new Date().toLocaleString("en-US")}`);

    workbook.sheets.forEach((sheet, sheetIndex) => {
      if (sheetIndex > 0) {
        doc.addPage();
      }

      doc.moveDown(1.5);
      doc.fontSize(18).fillColor("#111827").text(sheet.name);
      doc.moveDown(0.75);

      const rows = getSheetRows(sheet.rows);
      const headers = getSheetHeaders(rows);

      rows.forEach((row, rowIndex) => {
        ensurePdfSpace(doc, 110);
        doc
          .roundedRect(doc.x, doc.y, doc.page.width - doc.page.margins.left - doc.page.margins.right, 18, 6)
          .fill("#f8fafc");
        doc.fillColor("#0f172a").fontSize(11).text(`Row ${rowIndex + 1}`, doc.x + 10, doc.y + 5);
        doc.moveDown(1.6);

        headers.forEach((header) => {
          const value = row[header];

          if (value === null || value === undefined || value === "") {
            return;
          }

          ensurePdfSpace(doc, 32);
          doc.fontSize(10).fillColor("#6b7280").text(header, {
            continued: true
          });
          doc.fontSize(10).fillColor("#111827").text(`: ${String(value)}`);
        });

        doc.moveDown(0.6);
      });
    });

    doc.end();
  });
}

export async function createDownloadResponse(workbook: ExportWorkbook, format: "xlsx" | "csv" | "pdf") {
  const fileName = `${workbook.fileName}.${format}`;
  const body = format === "xlsx"
    ? createWorkbookBuffer(workbook)
    : format === "csv"
      ? createCsvText(workbook)
      : await createPdfBuffer(workbook);
  const contentType = format === "xlsx"
    ? "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    : format === "csv"
      ? "text/csv; charset=utf-8"
      : "application/pdf";

  return new Response(body, {
    headers: {
      "Content-Type": contentType,
      "Content-Disposition": `attachment; filename="${fileName}"`,
      "Cache-Control": "no-store"
    }
  });
}

export function isGoogleSheetsConfigured() {
  return Boolean(env.GOOGLE_SHEETS_CLIENT_EMAIL && env.GOOGLE_SHEETS_PRIVATE_KEY);
}

export async function publishWorkbookToGoogleSheets(workbook: ExportWorkbook, userEmail: string) {
  if (!isGoogleSheetsConfigured()) {
    throw new Error("Google Sheets export is not configured.");
  }

  const auth = new google.auth.JWT({
    email: env.GOOGLE_SHEETS_CLIENT_EMAIL,
    key: env.GOOGLE_SHEETS_PRIVATE_KEY?.replace(/\\n/g, "\n"),
    scopes: [
      "https://www.googleapis.com/auth/spreadsheets",
      "https://www.googleapis.com/auth/drive"
    ]
  });

  const sheets = google.sheets({ version: "v4", auth });
  const drive = google.drive({ version: "v3", auth });
  const spreadsheet = await sheets.spreadsheets.create({
    requestBody: {
      properties: {
        title: workbook.title
      },
      sheets: workbook.sheets.map((sheet) => ({
        properties: {
          title: sanitizeSheetName(sheet.name)
        }
      }))
    }
  });
  const spreadsheetId = spreadsheet.data.spreadsheetId;

  if (!spreadsheetId) {
    throw new Error("Google Sheets did not return a spreadsheet id.");
  }

  await sheets.spreadsheets.values.batchUpdate({
    spreadsheetId,
    requestBody: {
      valueInputOption: "RAW",
      data: workbook.sheets.map((sheet) => {
        const rows = getSheetRows(sheet.rows);
        const headers = Array.from(
          rows.reduce((keys, row) => {
            for (const key of Object.keys(row)) {
              keys.add(key);
            }

            return keys;
          }, new Set<string>())
        );

        return {
          range: `${sanitizeSheetName(sheet.name)}!A1`,
          values: [
            headers,
            ...rows.map((row) => headers.map((header) => row[header] ?? ""))
          ]
        };
      })
    }
  });

  await drive.permissions.create({
    fileId: spreadsheetId,
    requestBody: {
      role: "writer",
      type: "user",
      emailAddress: userEmail
    },
    sendNotificationEmail: false
  });

  if (env.GOOGLE_SHEETS_FOLDER_ID) {
    await drive.files.update({
      fileId: spreadsheetId,
      addParents: env.GOOGLE_SHEETS_FOLDER_ID
    });
  }

  return {
    spreadsheetId,
    url: `https://docs.google.com/spreadsheets/d/${spreadsheetId}/edit`
  };
}

export async function buildDashboardWorkbook(workspaceId: string): Promise<ExportWorkbook> {
  const data = await getDashboardData(workspaceId);

  return {
    fileName: "neolytics-dashboard",
    title: "Neolytics Dashboard Report",
    sheets: [
      {
        name: "Overview",
        rows: [
          { metric: "Catalog games", value: data.marketOverview.totalGames },
          { metric: "Average review score", value: data.marketOverview.averageReviewScore.toFixed(1) },
          { metric: "Tracked games", value: data.marketOverview.trackedGamesCount },
          { metric: "Recent launches", value: data.recentLaunches.length }
        ]
      },
      {
        name: "Tracked Games",
        rows: data.trackedGames.map((item) => ({
          game: item.steamGame.name,
          appId: item.steamGame.appId,
          reviewCount: item.steamGame.reviewCount ?? 0
        }))
      },
      {
        name: "Recent Launches",
        rows: data.recentLaunches.map((game) => ({
          game: game.name,
          appId: game.appId,
          releaseDate: formatDate(game.releaseDate)
        }))
      },
      {
        name: "Top Revenue",
        rows: data.topRevenue.map((item) => ({
          game: item.steamGame.name,
          appId: item.steamGame.appId,
          medianNetRevenueCents: item.medianNetRevenueCents,
          medianNetRevenueUsd: formatCurrency(item.medianNetRevenueCents)
        }))
      },
      {
        name: "Fastest Growing",
        rows: data.fastestGrowing.map((game) => ({
          game: game.name,
          appId: game.appId,
          reviewCount: game.reviewCount ?? 0
        }))
      }
    ]
  };
}

export async function buildFinanceWorkbook(organizationId: string): Promise<ExportWorkbook> {
  const data = await getFinanceOverview(organizationId);

  return {
    fileName: "finance-overview",
    title: "Neolytics Finance Overview",
    sheets: [
      {
        name: "Summary",
        rows: [
          { metric: "Active budgets", value: data.summary.activeBudgetsCount },
          { metric: "Planned budget", value: formatCurrency(data.summary.totalBudgetPlannedCents) },
          { metric: "Actual budget", value: formatCurrency(data.summary.totalBudgetActualCents) },
          { metric: "Revenue received", value: formatCurrency(data.summary.totalRevenueNetCents) },
          { metric: "Expenses paid", value: formatCurrency(data.summary.totalExpensesPaidCents) },
          { metric: "Pending receivables", value: formatCurrency(data.summary.pendingRevenueCents) },
          { metric: "Pending expense entries", value: formatCurrency(data.summary.pendingExpenseCents) },
          { metric: "Accounts payable open", value: formatCurrency(data.summary.payableOpenCents) },
          { metric: "Overdue payable titles", value: data.summary.overduePayablesCount },
          { metric: "Net cash", value: formatCurrency(data.summary.netCashCents) }
        ]
      },
      {
        name: "Cost Centers",
        rows: data.costCenters.map((costCenter) => ({
          code: costCenter.code,
          name: costCenter.name,
          active: costCenter.active ? "Yes" : "No"
        }))
      },
      {
        name: "Cash Flow",
        rows: data.cashflow.map((item) => ({
          month: item.month,
          inflowUsd: formatCurrency(item.inflowCents),
          outflowUsd: formatCurrency(item.outflowCents),
          netUsd: formatCurrency(item.netCents)
        }))
      },
      {
        name: "Budgets",
        rows: data.budgets.map((budget) => ({
          name: budget.name,
          project: budget.project?.name ?? "Organization-wide",
          status: budget.status,
          startsAt: formatDate(budget.startsAt),
          endsAt: formatDate(budget.endsAt),
          plannedUsd: formatCurrency(budget.totalPlannedCents),
          actualUsd: formatCurrency(budget.lines.reduce((sum, line) => sum + Number(line.actualCents), 0)),
          notes: budget.notes ?? ""
        }))
      },
      {
        name: "Budget Lines",
        rows: data.budgets.flatMap((budget) => budget.lines.map((line) => ({
          budget: budget.name,
          category: line.category,
          description: line.description,
          vendor: line.vendorName ?? "",
          plannedUsd: formatCurrency(line.plannedCents),
          actualUsd: formatCurrency(line.actualCents),
          dueAt: formatDate(line.dueAt),
          paidAt: formatDate(line.paidAt)
        })))
      },
      {
        name: "Revenue",
        rows: data.revenueEntries.map((entry) => ({
          project: entry.project?.name ?? "Organization-wide",
          sourceType: entry.sourceType,
          sourceName: entry.sourceName,
          status: entry.status,
          grossUsd: formatCurrency(entry.grossCents),
          netUsd: formatCurrency(entry.netCents),
          receivedAt: formatDate(entry.receivedAt),
          notes: entry.notes ?? ""
        }))
      },
      {
        name: "Revenue Channels",
        rows: data.commercialOperations.revenueChannels.map((channel) => ({
          sourceType: channel.sourceType,
          sourceName: channel.sourceName,
          entriesCount: channel.entriesCount,
          linkedProjectsCount: channel.linkedProjectsCount,
          grossUsd: formatCurrency(channel.grossCents),
          receivedUsd: formatCurrency(channel.receivedCents),
          pendingUsd: formatCurrency(channel.pendingCents),
          lastReceivedAt: formatDate(channel.lastReceivedAt)
        }))
      },
      {
        name: "Commercial Reconciliation",
        rows: [
          {
            metric: "Unlinked revenue entries",
            value: data.commercialOperations.reconciliation.unlinkedRevenueEntriesCount
          },
          {
            metric: "Open issued invoices",
            value: data.commercialOperations.reconciliation.openIssuedInvoicesCount
          },
          {
            metric: "Open issued invoice value",
            value: formatCurrency(data.commercialOperations.reconciliation.openIssuedInvoicesCents)
          },
          {
            metric: "Overdue issued invoices",
            value: data.commercialOperations.reconciliation.overdueIssuedInvoicesCount
          },
          {
            metric: "Pending royalty statements",
            value: data.commercialOperations.reconciliation.pendingRoyaltyStatementsCount
          },
          {
            metric: "Royalties due",
            value: formatCurrency(data.commercialOperations.reconciliation.royaltiesDueCents)
          }
        ]
      },
      {
        name: "Expenses",
        rows: data.expenseEntries.map((entry) => ({
          project: entry.project?.name ?? "Organization-wide",
          category: entry.category,
          vendorName: entry.vendorName,
          status: entry.status,
          amountUsd: formatCurrency(entry.amountCents),
          occurredAt: formatDate(entry.occurredAt),
          dueAt: formatDate(entry.dueAt),
          paidAt: formatDate(entry.paidAt),
          notes: entry.notes ?? ""
        }))
      },
      {
        name: "Accounts Payable",
        rows: data.payableTitles.map((title) => ({
          prefix: title.prefix,
          titleNumber: title.titleNumber,
          documentType: title.documentType,
          nature: title.natureDescription,
          supplierIdentifier: title.supplierIdentifier,
          supplierName: title.supplierName,
          project: title.project?.name ?? "Organization-wide",
          costCenter: `${title.costCenter.code} - ${title.costCenter.name}`,
          issueDate: formatDate(title.issueDate),
          dueDate: formatDate(title.dueDate),
          actualDueDate: formatDate(title.actualDueDate),
          titleAmountUsd: formatCurrency(title.titleAmountCents),
          additionalAmountUsd: formatCurrency(title.additionalAmountCents),
          totalAmountUsd: formatCurrency(title.totalAmountCents),
          paidAmountUsd: formatCurrency(title.paidAmountCents),
          openAmountUsd: formatCurrency(Math.max(Number(title.totalAmountCents) - Number(title.paidAmountCents), 0)),
          status: title.status,
          notes: title.notes ?? ""
        }))
      },
      {
        name: "Payable Allocations",
        rows: data.payableTitles.flatMap((title) =>
          title.allocations.map((allocation) => ({
            prefix: title.prefix,
            titleNumber: title.titleNumber,
            supplierName: title.supplierName,
            costCenter: `${allocation.costCenter.code} - ${allocation.costCenter.name}`,
            nature: allocation.natureDescription,
            amountUsd: formatCurrency(allocation.amountCents)
          }))
        )
      },
      {
        name: "Payable Payments",
        rows: data.payableTitles.flatMap((title) =>
          title.payments.map((payment) => ({
            prefix: title.prefix,
            titleNumber: title.titleNumber,
            supplierName: title.supplierName,
            paymentType: payment.paymentType,
            paymentDate: formatDate(payment.paymentDate),
            bank: payment.bank ?? "",
            branch: payment.branch ?? "",
            account: payment.account ?? "",
            amountPaidUsd: formatCurrency(payment.amountPaidCents),
            fineUsd: formatCurrency(payment.fineCents),
            interestUsd: formatCurrency(payment.interestCents),
            history: payment.history ?? ""
          }))
        )
      },
      {
        name: "Project PnL",
        rows: data.projectSnapshots.map((item) => ({
          project: item.projectName,
          stage: item.stage,
          budgetPlannedUsd: formatCurrency(item.budgetPlannedCents),
          budgetActualUsd: formatCurrency(item.budgetActualCents),
          revenueUsd: formatCurrency(item.revenueNetCents),
          expensesUsd: formatCurrency(item.expensesPaidCents),
          netUsd: formatCurrency(item.netCents)
        }))
      }
    ]
  };
}

export async function buildGameSearchWorkbook(input: {
  query?: string;
  genre?: string;
  tag?: string;
  minPrice?: number;
  maxPrice?: number;
  minReviewScore?: number;
  fromReleaseDate?: Date;
  toReleaseDate?: Date;
  page?: number;
  pageSize?: number;
}): Promise<ExportWorkbook> {
  const result = await searchGames({
    ...input,
    page: 1,
    pageSize: input.pageSize ?? 500
  });
  const appIds = result.items.map((game) => game.appId);
  const enrichedGames = await db.steamGame.findMany({
    where: {
      appId: {
        in: appIds
      }
    },
    include: {
      priceCurrent: true,
      salesEstimates: {
        orderBy: {
          calculatedAt: "desc"
        },
        take: 1
      },
      revenueEstimates: {
        orderBy: {
          calculatedAt: "desc"
        },
        take: 1
      },
      genres: {
        include: {
          steamGenre: true
        }
      },
      tags: {
        include: {
          steamTag: true
        }
      }
    }
  });
  const gamesByAppId = new Map(enrichedGames.map((game) => [game.appId, game]));
  const games = result.items.map((game) => gamesByAppId.get(game.appId) ?? game);
  const prices = games.map((game) => game.priceCurrent?.finalPriceCents ?? null).filter((value): value is number => value !== null);
  const reviewScores = games.map((game) => game.reviewScore ?? null).filter((value): value is number => value !== null);
  const reviewCounts = games.map((game) => game.reviewCount ?? 0);
  const revenues = games.map((game) => toNumber("revenueEstimates" in game ? game.revenueEstimates[0]?.medianNetRevenueCents : null)).filter((value) => value > 0);
  const shortlist = [...games]
    .map((game) => {
      const revenue = toNumber("revenueEstimates" in game ? game.revenueEstimates[0]?.medianNetRevenueCents : null);
      const score = Math.round(
        (game.reviewScore ?? 0) * 0.55
        + Math.min(25, Math.log10((game.reviewCount ?? 0) + 1) * 7)
        + Math.min(20, revenue / 2_500_000)
      );

      return {
        game,
        score,
        revenue
      };
    })
    .sort((left, right) => right.score - left.score)
    .slice(0, 25);
  const priceBands = [
    { band: "Free / unknown", min: null, max: 0 },
    { band: "Under $10", min: 1, max: 999 },
    { band: "$10-$20", min: 1000, max: 1999 },
    { band: "$20-$30", min: 2000, max: 2999 },
    { band: "$30+", min: 3000, max: null }
  ].map((band) => {
    const bandGames = games.filter((game) => {
      const price = game.priceCurrent?.finalPriceCents ?? 0;

      if (band.min === null) {
        return price <= (band.max ?? 0);
      }

      if (band.max === null) {
        return price >= band.min;
      }

      return price >= band.min && price <= band.max;
    });

    return {
      band: band.band,
      games: bandGames.length,
      avgReviewScore: Math.round(average(bandGames.map((game) => game.reviewScore ?? 0))),
      medianReviews: Math.round(median(bandGames.map((game) => game.reviewCount ?? 0))),
      medianRevenueUsd: formatCurrency(median(bandGames.map((game) => toNumber("revenueEstimates" in game ? game.revenueEstimates[0]?.medianNetRevenueCents : null)).filter((value) => value > 0)))
    };
  });
  const tagCounts = new Map<string, { count: number; reviewScoreTotal: number; revenueTotal: number }>();

  for (const game of games) {
    for (const tag of game.tags.map((item) => item.steamTag.name)) {
      const current = tagCounts.get(tag) ?? { count: 0, reviewScoreTotal: 0, revenueTotal: 0 };
      current.count += 1;
      current.reviewScoreTotal += game.reviewScore ?? 0;
      current.revenueTotal += toNumber("revenueEstimates" in game ? game.revenueEstimates[0]?.medianNetRevenueCents : null);
      tagCounts.set(tag, current);
    }
  }

  return {
    fileName: "steam-games-search",
    title: "Steam Games Search Export",
    sheets: [
      {
        name: "Executive Read",
        rows: [
          { metric: "Games exported", value: games.length },
          { metric: "Total matched in database", value: result.total },
          { metric: "Median price", value: formatCurrency(median(prices)) },
          { metric: "Average review score", value: `${average(reviewScores).toFixed(1)}%` },
          { metric: "Median review count", value: Math.round(median(reviewCounts)) },
          { metric: "Median estimated revenue", value: formatCurrency(median(revenues)) },
          {
            metric: "Quality read",
            value: average(reviewScores) >= 80 ? "The exported segment has a strong quality bar." : "The exported segment has quality gaps; inspect leaders before copying patterns."
          },
          {
            metric: "Commercial read",
            value: revenues.length > 0 ? "Revenue estimates are available for part of this set; use the shortlist to prioritize deeper comparison." : "Revenue estimate coverage is thin; use reviews and price as the primary signal."
          },
          {
            metric: "Recommended next action",
            value: shortlist[0] ? `Start by comparing ${shortlist[0].game.name} against the top 5 shortlist titles.` : "Refine filters and export again with a clearer segment."
          }
        ]
      },
      {
        name: "Opportunity Shortlist",
        rows: shortlist.map((item, index) => ({
          rank: index + 1,
          appId: item.game.appId,
          name: item.game.name,
          signalScore: item.score,
          signal: getSignalLabel(item.game.reviewScore, item.game.reviewCount),
          priceUsd: formatCurrency(item.game.priceCurrent?.finalPriceCents ?? null),
          reviewScore: item.game.reviewScore ?? null,
          reviewCount: item.game.reviewCount ?? null,
          medianSales: "salesEstimates" in item.game ? item.game.salesEstimates[0]?.medianEstimate ?? null : null,
          medianRevenueUsd: formatCurrency(item.revenue),
          genres: item.game.genres.map((genre) => genre.steamGenre.name).join(", "),
          tags: item.game.tags.slice(0, 8).map((tag) => tag.steamTag.name).join(", ")
        }))
      },
      {
        name: "Pricing Bands",
        rows: priceBands
      },
      {
        name: "Tag Signals",
        rows: Array.from(tagCounts.entries())
          .map(([tag, data]) => ({
            tag,
            games: data.count,
            avgReviewScore: Math.round(data.reviewScoreTotal / data.count),
            totalEstimatedRevenueUsd: formatCurrency(data.revenueTotal),
            read: data.count >= 5 ? "Recurring segment signal" : "Niche/edge signal"
          }))
          .sort((left, right) => right.games - left.games)
          .slice(0, 40)
      },
      {
        name: "Games",
        rows: games.map((game) => ({
          appId: game.appId,
          name: game.name,
          genres: game.genres.map((genre) => genre.steamGenre.name).join(", "),
          tags: game.tags.slice(0, 12).map((tag) => tag.steamTag.name).join(", "),
          priceCents: game.priceCurrent?.finalPriceCents ?? null,
          priceUsd: formatCurrency(game.priceCurrent?.finalPriceCents ?? null),
          reviewScore: game.reviewScore ?? null,
          reviewCount: game.reviewCount ?? null,
          releaseDate: formatDate(game.releaseDate),
          medianSales: "salesEstimates" in game ? game.salesEstimates[0]?.medianEstimate ?? null : null,
          medianRevenueUsd: formatCurrency("revenueEstimates" in game ? game.revenueEstimates[0]?.medianNetRevenueCents ?? null : null),
          signal: getSignalLabel(game.reviewScore, game.reviewCount)
        }))
      }
    ]
  };
}

export async function buildGameWorkbook(appId: number): Promise<ExportWorkbook> {
  const [game, priceHistory, reviewHistory, playerHistory] = await Promise.all([
    getGameByAppId(appId),
    getPriceHistory(appId),
    getReviewHistory(appId),
    getPlayerHistory(appId)
  ]);

  if (!game) {
    throw new Error("Game not found.");
  }

  const latestSalesEstimate = game.salesEstimates[0] ?? null;
  const latestRevenueEstimate = game.revenueEstimates[0] ?? null;
  const firstReviewSnapshot = reviewHistory[0] ?? null;
  const latestReviewSnapshot = reviewHistory[reviewHistory.length - 1] ?? null;
  const firstPlayerSnapshot = playerHistory[0] ?? null;
  const latestPlayerSnapshot = playerHistory[playerHistory.length - 1] ?? null;
  const reviewDelta = latestReviewSnapshot && firstReviewSnapshot ? latestReviewSnapshot.totalReviews - firstReviewSnapshot.totalReviews : null;
  const playerDelta = latestPlayerSnapshot && firstPlayerSnapshot ? latestPlayerSnapshot.currentPlayers - firstPlayerSnapshot.currentPlayers : null;
  const discountEvents = priceHistory.filter((item) => (item.discountPercent ?? 0) > 0);
  const lowestObservedPrice = median(priceHistory.map((item) => item.finalPriceCents ?? 0).filter((value) => value > 0));
  const executiveSignals = [
    {
      signal: "Market role",
      read: getSignalLabel(game.reviewScore, game.reviewCount),
      implication: "Use this role to decide whether the game is a benchmark, warning sign, or watchlist reference."
    },
    {
      signal: "Quality bar",
      read: game.reviewScore ? `${game.reviewScore}% across ${game.reviewCount ?? 0} reviews` : "Review quality unavailable",
      implication: (game.reviewScore ?? 0) >= 80 ? "Audience reception is strong enough to study feature promises and store positioning." : "Treat this as a cautionary comp unless demand is unusually high."
    },
    {
      signal: "Commercial range",
      read: latestRevenueEstimate ? `${formatCurrency(latestRevenueEstimate.lowNetRevenueCents)} - ${formatCurrency(latestRevenueEstimate.highNetRevenueCents)}` : "Revenue estimate unavailable",
      implication: latestRevenueEstimate ? "Use the median estimate as a planning anchor, not a forecast guarantee." : "Do not use this title for revenue planning until estimates are available."
    },
    {
      signal: "Price posture",
      read: `${formatCurrency(game.priceCurrent?.finalPriceCents ?? null)} current price${discountEvents.length > 0 ? `, ${discountEvents.length} observed discount snapshots` : ""}`,
      implication: discountEvents.length > 0 ? "Discount behavior is visible; compare timing against review/player movement." : "No discount cadence is visible in the export window."
    },
    {
      signal: "Momentum",
      read: `Reviews ${reviewDelta === null ? "unknown" : reviewDelta >= 0 ? `+${reviewDelta}` : String(reviewDelta)}, players ${playerDelta === null ? "unknown" : playerDelta >= 0 ? `+${playerDelta}` : String(playerDelta)}`,
      implication: (reviewDelta ?? 0) > 0 || (playerDelta ?? 0) > 0 ? "There is observable movement worth checking against content updates or discounts." : "Momentum is flat in available snapshots."
    }
  ];

  return {
    fileName: `steam-game-${appId}`,
    title: `${game.name} Report`,
    sheets: [
      {
        name: "Executive Read",
        rows: executiveSignals
      },
      {
        name: "Operating Actions",
        rows: [
          {
            priority: "High",
            action: "Compare store promise",
            reason: `Use ${game.name}'s capsule, tags, price, and review score as a direct bar for positioning.`,
            output: "One positioning note: copy, avoid, or outflank."
          },
          {
            priority: latestRevenueEstimate ? "High" : "Medium",
            action: "Set revenue planning band",
            reason: latestRevenueEstimate ? `Median net revenue estimate is ${formatCurrency(latestRevenueEstimate.medianNetRevenueCents)}.` : "Revenue estimate is unavailable.",
            output: "Low/base/high planning range for project forecast."
          },
          {
            priority: discountEvents.length > 0 ? "Medium" : "Low",
            action: "Review discount timing",
            reason: discountEvents.length > 0 ? `${discountEvents.length} discount snapshots observed; median observed paid price is ${formatCurrency(lowestObservedPrice)}.` : "No discount pattern observed.",
            output: "Pricing and discount assumption for launch/post-launch model."
          },
          {
            priority: "Medium",
            action: "Extract feature promises from tags",
            reason: game.tags.length > 0 ? `Dominant tags: ${game.tags.slice(0, 8).map((tag) => tag.steamTag.name).join(", ")}.` : "Tag coverage is thin.",
            output: "Feature promise checklist for concept comparison."
          }
        ]
      },
      {
        name: "Overview",
        rows: [
          { field: "App ID", value: game.appId },
          { field: "Name", value: game.name },
          { field: "Description", value: game.shortDescription ?? "" },
          { field: "Release date", value: formatDate(game.releaseDate) },
          { field: "Genres", value: game.genres.map((genre) => genre.steamGenre.name).join(", ") },
          { field: "Developers", value: game.developers.map((developer) => developer.steamDeveloper.name).join(", ") },
          { field: "Publishers", value: game.publishers.map((publisher) => publisher.steamPublisher.name).join(", ") },
          { field: "Current price", value: formatCurrency(game.priceCurrent?.finalPriceCents ?? null) },
          { field: "Review score", value: game.reviewScore ?? "" },
          { field: "Review count", value: game.reviewCount ?? "" },
          { field: "Current players", value: game.currentPlayers ?? "" },
          { field: "Estimated median sales", value: latestSalesEstimate?.medianEstimate ?? "" },
          { field: "Estimated median net revenue", value: formatCurrency(latestRevenueEstimate?.medianNetRevenueCents ?? null) }
        ]
      },
      {
        name: "Price History",
        rows: priceHistory.map((item) => ({
          snapshotDate: formatDate(item.snapshotDate),
          finalPriceCents: item.finalPriceCents ?? null,
          finalPriceUsd: formatCurrency(item.finalPriceCents ?? null),
          initialPriceCents: item.initialPriceCents ?? null,
          discountPercent: item.discountPercent ?? null,
          currency: item.currency ?? ""
        }))
      },
      {
        name: "Review History",
        rows: reviewHistory.map((item) => ({
          snapshotDate: formatDate(item.snapshotDate),
          totalReviews: item.totalReviews,
          totalPositiveReviews: item.totalPositiveReviews,
          totalNegativeReviews: item.totalNegativeReviews,
          reviewScore: item.reviewScore ?? null,
          reviewScoreLabel: item.reviewScoreLabel
        }))
      },
      {
        name: "Player History",
        rows: playerHistory.map((item) => ({
          snapshotDate: formatDate(item.snapshotDate),
          currentPlayers: item.currentPlayers
        }))
      },
      {
        name: "Estimates",
        rows: [
          {
            type: "Sales",
            low: latestSalesEstimate?.lowEstimate ?? null,
            median: latestSalesEstimate?.medianEstimate ?? null,
            high: latestSalesEstimate?.highEstimate ?? null,
            confidence: latestSalesEstimate?.confidence ?? "",
            explanation: latestSalesEstimate?.explanation ?? ""
          },
          {
            type: "Revenue",
            low: latestRevenueEstimate ? Number(latestRevenueEstimate.lowNetRevenueCents) : null,
            median: latestRevenueEstimate ? Number(latestRevenueEstimate.medianNetRevenueCents) : null,
            high: latestRevenueEstimate ? Number(latestRevenueEstimate.highNetRevenueCents) : null,
            confidence: latestRevenueEstimate?.confidence ?? "",
            explanation: latestRevenueEstimate?.explanation ?? ""
          }
        ]
      }
    ]
  };
}

export async function buildCompareWorkbook(appIds: number[]): Promise<ExportWorkbook> {
  const games = await compareGames(appIds);

  return {
    fileName: "steam-games-compare",
    title: "Steam Games Comparison",
    sheets: [
      {
        name: "Comparison",
        rows: games.map((game) => ({
          appId: game.appId,
          name: game.name,
          priceUsd: formatCurrency(game.priceCurrent?.finalPriceCents ?? null),
          reviewScore: game.reviewScore ?? null,
          reviewCount: game.reviewCount ?? null,
          medianSales: game.salesEstimates[0]?.medianEstimate ?? null,
          medianNetRevenueUsd: formatCurrency(game.revenueEstimates[0]?.medianNetRevenueCents ?? null),
          genres: game.genres.map((genre) => genre.steamGenre.name).join(", ")
        }))
      }
    ]
  };
}

export async function buildOpportunitiesWorkbook(): Promise<ExportWorkbook> {
  const items = await getOpportunityFinderData();

  return {
    fileName: "steam-opportunities",
    title: "Steam Opportunity Finder",
    sheets: [
      {
        name: "Opportunities",
        rows: items.map((item) => ({
          appId: item.appId,
          name: item.name,
          opportunityScore: item.score,
          reviewScore: item.reviewScore ?? null,
          competitionCount: item.competitionCount,
          medianNetRevenueUsd: formatCurrency(item.medianNetRevenueCents),
          priceUsd: formatCurrency(item.priceCents)
        }))
      }
    ]
  };
}

export async function buildProjectWorkbook(projectId: string, workspaceId: string): Promise<ExportWorkbook> {
  const project = await getProjectById(projectId, workspaceId);

  if (!project) {
    throw new Error("Project not found.");
  }

  const latestGdd = project.gdds[0] ?? null;
  const board = project.kanbanBoards[0] ?? null;

  return {
    fileName: `project-${project.slug}`,
    title: `${project.name} Project Report`,
    sheets: [
      {
        name: "Project",
        rows: [
          { field: "Name", value: project.name },
          { field: "Stage", value: project.stage },
          { field: "Elevator pitch", value: project.elevatorPitch ?? "" },
          { field: "Description", value: project.description ?? "" },
          { field: "Genres", value: project.genreInput ?? "" },
          { field: "Tags", value: project.tagInput ?? "" },
          { field: "Target audience", value: project.targetAudience ?? "" },
          { field: "Core loop", value: project.coreLoop ?? "" },
          { field: "Differentiator", value: project.differentiator ?? "" },
          { field: "Monetization", value: project.monetizationModel ?? "" },
          { field: "Art direction", value: project.artDirection ?? "" },
          { field: "Player fantasy", value: project.playerFantasy ?? "" },
          { field: "Price target", value: formatCurrency(project.pricePointCents ?? null) }
        ]
      },
      {
        name: "Market Analysis",
        rows: project.analysis ? [
          {
            analyzedAt: formatDate(project.analysis.analyzedAt),
            matchingGamesCount: project.analysis.matchingGamesCount,
            competitionCount: project.analysis.competitionCount,
            releaseMomentum: project.analysis.releaseMomentum,
            averageReviewScore: project.analysis.averageReviewScore ?? null,
            averagePriceUsd: formatCurrency(project.analysis.averagePriceCents ?? null),
            medianRevenueUsd: formatCurrency(project.analysis.medianRevenueCents ?? null),
            opportunitySummary: project.analysis.opportunitySummary,
            riskSummary: project.analysis.riskSummary,
            audienceAutofill: project.analysis.audienceAutofill ?? "",
            coreLoopAutofill: project.analysis.coreLoopAutofill ?? "",
            suggestedGenres: Array.isArray(project.analysis.suggestedGenres) ? project.analysis.suggestedGenres.join(", ") : "",
            suggestedTags: Array.isArray(project.analysis.suggestedTags) ? project.analysis.suggestedTags.join(", ") : ""
          }
        ] : []
      },
      {
        name: "Comparable Games",
        rows: project.competitorGames.map((item) => ({
          appId: item.steamGame.appId,
          name: item.steamGame.name,
          reviewScore: item.steamGame.reviewScore ?? null,
          reviewCount: item.steamGame.reviewCount ?? null,
          medianNetRevenueUsd: formatCurrency(item.steamGame.revenueEstimates[0]?.medianNetRevenueCents ?? null)
        }))
      },
      {
        name: "GDD",
        rows: latestGdd ? latestGdd.content.split("\n").map((line, index) => ({
          line: index + 1,
          content: line
        })) : []
      },
      {
        name: "Kanban",
        rows: board
          ? board.columns.flatMap((column) => {
              if (column.cards.length === 0) {
                return [{
                  column: column.name,
                  title: "",
                  assignee: "",
                  dueDate: "",
                  labels: ""
                }];
              }

              return column.cards.map((card) => ({
                column: column.name,
                title: card.title,
                assignee: card.assigneeLabel ?? "",
                dueDate: formatDate(card.dueDate),
                labels: Array.isArray(card.labels) ? card.labels.join(", ") : ""
              }));
            })
          : []
      }
    ]
  };
}

export async function buildReportWorkbook(reportId: string, organizationId: string): Promise<ExportWorkbook> {
  const report = await db.aiReport.findFirst({
    where: {
      id: reportId,
      organizationId
    }
  });

  if (!report) {
    throw new Error("Report not found.");
  }

  const metadata = (report.metadata ?? {}) as {
    segment?: Record<string, unknown>;
    aiNarrative?: {
      executiveSummary?: string;
      demandDrivers?: string;
      saturationRead?: string;
      pricingRead?: string;
      launchWindowAdvice?: string;
      monetizationRead?: string;
      confidenceNarrative?: string;
      actionItems?: string[];
    } | null;
    operatingBrief?: {
      boardDirective?: string;
      commercialDirective?: string;
      operatingDirective?: string;
    } | null;
    planLabel?: string;
  };
  const segment = metadata.segment ?? {};
  const aiNarrative = metadata.aiNarrative ?? null;
  const operatingBrief = metadata.operatingBrief ?? null;

  return {
    fileName: `report-${report.id}`,
    title: report.title,
    sheets: [
      {
        name: "Summary",
        rows: [
          { field: "Title", value: report.title },
          { field: "Type", value: report.reportType },
          { field: "Status", value: report.status },
          { field: "Subject", value: report.subject },
          { field: "Created at", value: formatDate(report.createdAt) },
          { field: "Updated at", value: formatDate(report.updatedAt) }
        ]
      },
      {
        name: "Decision Brief",
        rows: [
          { area: "Executive summary", recommendation: aiNarrative?.executiveSummary ?? (report.content ?? "").split("\n").find((line) => line.trim().length > 0) ?? "" },
          { area: "Demand drivers", recommendation: aiNarrative?.demandDrivers ?? "" },
          { area: "Saturation", recommendation: aiNarrative?.saturationRead ?? "" },
          { area: "Pricing", recommendation: aiNarrative?.pricingRead ?? "" },
          { area: "Launch window", recommendation: aiNarrative?.launchWindowAdvice ?? "" },
          { area: "Monetization", recommendation: aiNarrative?.monetizationRead ?? "" },
          { area: "Confidence", recommendation: aiNarrative?.confidenceNarrative ?? "" },
          { area: "Board directive", recommendation: operatingBrief?.boardDirective ?? "" },
          { area: "Commercial directive", recommendation: operatingBrief?.commercialDirective ?? "" },
          { area: "Operating directive", recommendation: operatingBrief?.operatingDirective ?? "" }
        ].filter((row) => row.recommendation)
      },
      {
        name: "Market Metrics",
        rows: Object.entries(segment).map(([metric, value]) => ({
          metric,
          value: typeof value === "object" ? JSON.stringify(value) : String(value ?? "")
        }))
      },
      {
        name: "Action Items",
        rows: (aiNarrative?.actionItems ?? []).map((item, index) => ({
          priority: index + 1,
          action: item,
          owner: "",
          status: "Open"
        }))
      },
      {
        name: "Content",
        rows: (report.content ?? "").split("\n").map((line, index) => ({
          line: index + 1,
          content: line
        }))
      }
    ]
  };
}
